"""Second product batch (added 2 Oct 2026, doubles the catalog).

ASIN: (display name, theme, ages "min-max", top pick?, blurb)
Data (price, rating, reviews, image) comes from data/batch2_2026-10-02.txt.
"""

ED2 = {
    # ---------- Family games ----------
    "B07P6MZPK3": ("UNO Card Game", "games", "7-99", True,
                   "The classic match-the-color card game. Easy for kids, fun for grandparents, under $12."),
    "B010TQY7A8": ("Exploding Kittens Card Game", "games", "7-99", False,
                   "A silly, fast strategy card game where you avoid the exploding kitten. A family-night favorite."),
    "B003I64OT6": ("LCR Left Center Right Dice Game", "games", "5-99", False,
                   "Roll, pass chips and hope you're last one standing. Simple, loud fun for big family gatherings."),
    "B00TLEMRKM": ("Yahtzee Dice Game", "games", "8-99", False,
                   "The classic dice game that sneaks in a little math. Quick to learn, good for all ages."),
    "B00D7OAOYI": ("Trouble Board Game", "games", "5-15", False,
                   "Pop-O-Matic dice and race-home rules make this a great first board game for young kids."),
    "B00NQQTZCO": ("Monopoly Deal Card Game", "games", "8-99", False,
                   "All the fun of Monopoly in about 15 minutes. A pocket-size stocking stuffer."),
    "B00000IZJB": ("Rummikub Tile Game", "games", "8-99", False,
                   "The classic rummy tile game that rewards planning. Kids quickly learn to beat the adults."),
    "B076HK9H7Z": ("Sorry! Board Game", "games", "6-99", False,
                   "Slide, bump and say 'Sorry!' in this family classic, now under $10."),
    "B07Y98CFPB": ("Giant UNO Card Game", "games", "7-99", False,
                   "UNO with cards three times bigger. Hilarious for parties, holidays and little hands."),
    "1932188126": ("Bananagrams Word Game", "games", "7-99", False,
                   "A fast crossword race in a banana pouch. Great for spelling practice and travel."),
    "B06XY881H4": ("Connect 4 Game", "games", "6-99", False,
                   "Drop the discs and get four in a row. A quick two-player strategy classic."),
    "B0C3DNT9W3": ("Hungry Hungry Hippos", "games", "4-8", False,
                   "Chomp the marbles as fast as you can. A noisy, giggly first game for preschoolers."),
    "B0D2LCR5ZM": ("Skillmatics Search and Find: Disney Princess", "games", "3-6", False,
                   "A seek-and-find preschool game with Disney Princess scenes that builds focus and vocabulary."),
    # ---------- Early learning (baby & toddler) ----------
    "B00Y53V80E": ("VTech Turn and Learn Driver", "learning", "0-3", True,
                   "A pretend steering wheel with songs, lights and sounds. Toddlers love 'driving' like mom and dad."),
    "B00005C5H4": ("The First Years Stack & Count Cups", "learning", "0-3", False,
                   "Eight numbered stacking cups for building, nesting and bath play. Over 90,000 ratings."),
    "B078WM314M": ("Learning Resources Spike the Fine Motor Hedgehog", "learning", "1-4", True,
                   "Kids put colorful quills into a friendly hedgehog, building fine motor skills and color matching."),
    "B007XVYPS2": ("VTech Spin and Learn Color Flashlight", "learning", "1-3", False,
                   "A toddler-safe flashlight that projects colors and plays songs. A favorite for bedtime and car rides."),
    "B06WV7VBY5": ("VTech Pop-a-Balls Push and Pop Bulldozer", "learning", "1-3", False,
                   "Push the bulldozer and balls pop out the top. Encourages crawling and walking."),
    "B01NCUSC7V": ("Fisher-Price Baby's First Blocks", "learning", "0-3", False,
                   "Shape-sorting bucket with 10 chunky blocks. A classic first toy that's under $12."),
    "B08ZR65PLQ": ("Numberblocks 1-10 MathLink Cubes Set", "learning", "3-6", False,
                   "Build the Numberblocks characters from the show and learn counting and early math."),
    "B00006JZCG": ("Melissa & Doug Pattern Blocks and Boards", "learning", "3-6", False,
                   "120 wooden shapes and pattern boards that teach shapes, colors and problem solving."),
    "B081GTG1ZW": ("Magnetic Letter Board with ABC Letters", "learning", "3-6", False,
                   "A double-sided magnetic board with letters for spelling, drawing and early reading practice."),
    "B003N9M6YI": ("Nuby Ice Gel Teether Keys", "learning", "0-1", False,
                   "Chill them in the fridge to soothe sore gums. A tiny, top-rated stocking stuffer for babies."),
    "B008J1QP7Y": ("Bright Starts Oball Shaker Rattle", "learning", "0-1", False,
                   "The easy-grip Oball with a rattle inside. Perfect for tiny hands that are just learning to grasp."),
    "B000JWSO9I": ("RaZbaby RaZberry Silicone Teether", "learning", "0-1", False,
                   "A soft, bumpy silicone teether that babies can hold on their own. Under $5."),
    "B08X1YQ2N9": ("Suction Cup Spinner Toys", "learning", "1-3", False,
                   "Spinners that stick to high chairs, tables and windows. Keeps toddlers busy at restaurants and on flights."),
    "B07DPBB4CT": ("Baby Einstein Sticky Spinner High Chair Toy", "learning", "0-2", False,
                   "A suction-cup spinner for the high chair tray that keeps little ones entertained during meals."),
    "B000EK59H0": ("Melissa & Doug First Shapes Jumbo Knob Puzzle", "learning", "1-3", False,
                   "Big wooden knobs and simple shapes, the perfect first puzzle for toddlers."),
    "B000E9DPCW": ("Melissa & Doug Farm Animals Chunky Puzzle", "learning", "2-4", False,
                   "Thick wooden farm animals that stand up for pretend play after the puzzle is done."),
    "B0BQD5PPX7": ("Numberblocks Friends One to Five Figures", "learning", "3-6", False,
                   "Five Numberblocks figures from the hit show. Great for counting games and story play."),
    "B06XKW173X": ("Fisher-Price Little People Surprise & Sounds Home", "learning", "1-5", False,
                   "A musical dollhouse with figures, lights and sounds made for toddler hands."),
    "B08LZRB2MS": ("Amazon Basics Ball Pit Balls with Storage Bag", "learning", "1-5", False,
                   "Crush-proof, BPA-free balls for ball pits, tents and kiddie pools, with a mesh storage bag."),
    "B00TYO5UKI": ("Terra Wild Animal Figures", "learning", "3-8", False,
                   "A set of realistic wild animal figures for safari adventures and animal-loving kids."),
    # ---------- Music ----------
    "B0BGJFB1C5": ("FOKI Floor Piano Mat", "music", "1-3", False,
                   "A big musical mat toddlers play with their feet. Dancing and music in one."),
    "B08V8F6Q9W": ("VTech Zoo Jamz Tiger Rock Guitar", "music", "1-4", False,
                   "A toddler guitar with real strings to strum, songs and light-up keys."),
    "B07W4H8N39": ("Kids Musical Instruments 33-Piece Set", "music", "3-8", False,
                   "Wooden percussion instruments for a whole family band, from maracas to a xylophone."),
    "B00005RF5C": ("Melissa & Doug Band-in-a-Box", "music", "3-6", False,
                   "Ten real instruments in a storage box: cymbals, tambourine, maracas and more."),
    "B08GJP4HHB": ("Amazmic Kids Karaoke Microphone", "music", "3-12", False,
                   "A Bluetooth karaoke microphone with built-in speaker and voice effects. Sing along to any song."),
    "B0CGRRGY6S": ("IROO Mini Karaoke Machine", "music", "4-12", False,
                   "A small karaoke speaker with a microphone and lights for little performers."),
    # ---------- LEGO & building ----------
    "B075QRWRYP": ("LEGO Classic Creative Suitcase", "building", "4-99", False,
                   "A LEGO suitcase with sorting trays and colorful bricks. Building on the go, under $12."),
    "B000CBSNKQ": ("MAGNA-TILES Classic 32-Piece Set", "building", "3-8", True,
                   "The original magnetic tiles. Durable, open-ended and loved by teachers and parents."),
    "B09FMW7FFF": ("LEGO City Police Car", "building", "5-8", False,
                   "A quick police car build with a minifigure. A perfect first LEGO set for 5-year-olds."),
    "B0BLJ3LHCH": ("LEGO Creator 3-in-1 Exotic Parrot", "building", "7-12", False,
                   "Build a parrot, a frog or a fish. Three models in one colorful box."),
    "B09LY1LNGJ": ("Soyee Magnetic Tiles for Toddlers", "building", "3-6", False,
                   "Big magnetic tiles sized for toddlers and preschoolers. Great value starter set."),
    "B0DJ19VGDH": ("LEGO Minecraft The Baby Pig House", "building", "7-12", False,
                   "A pig-shaped Minecraft house with Alex and baby pigs. A fan favorite under $15."),
    "B0CV2HGNY9": ("LEGO Speed Champions Mercedes-AMG G 63 & SL 63", "building", "10-99", False,
                   "Two detailed Mercedes models in one set for young car fans and collectors."),
    "B0DJ197ZQY": ("LEGO Technic Bush Plane", "building", "8-12", False,
                   "A small Technic airplane with a moving propeller. A great first Technic build."),
    "B0CV2FLSXB": ("LEGO Technic Koenigsegg Jesko Absolut", "building", "10-99", False,
                   "A detailed Technic hypercar for car fans 10 and up. A cool desk display."),
    "B0CGY22J6Y": ("LEGO Star Wars R2-D2", "building", "10-99", True,
                   "A big buildable R2-D2 display model. A showpiece for Star Wars fans 10 and up."),
    "B0CGXZ79WH": ("LEGO Star Wars Clone Trooper & Battle Droid Battle Pack", "building", "7-12", False,
                   "Four minifigures and a speeder for instant Star Wars battles. Under $25."),
    "B0D5JZDKXB": ("LEGO Disney and Pixar Up House", "building", "9-99", False,
                   "The house from Up, floating on colorful balloons. A sweet build for Pixar fans of any age."),
    "B0DJ1BM6YR": ("LEGO Disney Moana 2 Heihei", "building", "9-99", False,
                   "A buildable, posable Heihei the rooster from Moana 2."),
    "B0CGY26D8G": ("LEGO Disney Stitch", "building", "9-99", True,
                   "A big buildable Stitch with movable ears and head. One of the most popular LEGO gifts."),
    "B0DJ1B7RWD": ("LEGO Marvel Spider-Man Mech vs. Anti-Venom", "superheroes", "6-10", False,
                   "A posable Spider-Man mech and Anti-Venom minifigure for epic battles. Under $15."),
    # ---------- STEM & science ----------
    "B097F49QYH": ("Learning Resources STEM Explorers Brainometry", "stem", "5-10", False,
                   "Geometric pieces and challenge cards that build spatial reasoning through play."),
    "B07R92KFZR": ("National Geographic Glowing Marble Run", "stem", "8-12", True,
                   "A big marble run with glow-in-the-dark marbles. Kids design the track and learn physics."),
    "B0CKKXBKXN": ("JOYIN Glowing Marble Run with Elevator", "stem", "3-8", False,
                   "A 236-piece marble run with a motorized elevator that keeps the marbles rolling."),
    "B084R8X13B": ("National Geographic Mega Crystal Growing Kit", "stem", "8-12", False,
                   "Grow six colorful crystals and learn how they form. A favorite science gift."),
    "B09PB1KMHN": ("Light-Up Crystal Growing Kit", "stem", "8-12", False,
                   "Grow crystals, then light them up with an LED stand for a glowing night light."),
    "B01LQCIL88": ("National Geographic Hobby Rock Tumbler", "stem", "8-14", True,
                   "Turn rough rocks into shiny gemstones. A long-term project curious kids love."),
    "B00SK5RUQY": ("Makeblock mBot Coding Robot", "stem", "8-12", False,
                   "Build a robot and program it with drag-and-drop blocks. A real first step into coding."),
    "B083T58PKM": ("Learning Resources Botley 2.0 Coding Robot", "stem", "5-10", False,
                   "A screen-free coding robot that teaches young kids sequences and logic."),
    "B00SKURVKY": ("Wonder Workshop Dash Coding Robot", "stem", "6-11", False,
                   "A talking robot kids program with free apps. Used in thousands of classrooms."),
    "B0D24LTPS7": ("National Geographic Kids Magic Kit", "stem", "8-12", False,
                   "45 magic tricks with the science behind them. Kids learn, then perform for the family."),
    "B0CCQCSBY8": ("National Geographic Starter Metal Detector", "stem", "6-12", False,
                   "A lightweight metal detector sized for kids, made for backyard and beach treasure hunts."),
    # ---------- Dinosaurs ----------
    "B09B1QZLXW": ("Bouncy Pals Dinosaur Hopper", "dinosaurs", "1-3", False,
                   "A soft dinosaur ride-on toddlers bounce on. Burns energy indoors on rainy days."),
    "B07WLLHHZ8": ("National Geographic Dinosaur Dig Kit", "dinosaurs", "8-12", False,
                   "Twelve dinosaur eggs to excavate, each with a surprise dino inside."),
    "B07T2ZFNPL": ("Dig Up Dinosaur Fossil Eggs", "dinosaurs", "3-8", False,
                   "A dozen dig-out eggs with dinosaur figures. Messy, exciting fun for young paleontologists."),
    "B08JCM9ZW3": ("Dinosaur Fossil Digging Kit", "dinosaurs", "6-12", False,
                   "Excavate dinosaur skeletons with real digging tools, then assemble them."),
    # ---------- Outdoor & active ----------
    "B08ZCM11J6": ("Jetson Jupiter Kids Light-Up Kick Scooter", "outdoor", "5-12", False,
                   "A foldable light-up kick scooter with over 24,000 ratings on Amazon."),
    "B07VY9Q95Q": ("Hurtle 3-Wheeled Scooter with LED Wheels", "outdoor", "3-6", False,
                   "A stable three-wheel scooter with light-up wheels and adjustable height for little riders."),
    "B08SGH7NKX": ("SEREED Baby Balance Bike", "outdoor", "1-2", False,
                   "A first bike for 1-year-olds that builds balance and confidence before pedals."),
    "B008CO80SA": ("Step2 Whisper Ride II Push Car", "outdoor", "1-3", False,
                   "A quiet-wheel push car with a parent handle and seat belt. Great for walks and the yard."),
    "B07P6YHBQD": ("Roller Derby Firestar Adjustable Youth Skates", "outdoor", "5-12", False,
                   "Adjustable quad skates that grow up to four sizes. A smart first pair."),
    "B01K1K0K6M": ("Step2 Rain Showers Splash Pond Water Table", "outdoor", "1-5", False,
                   "A water table with a rain-shower tower. Hours of backyard splashing for toddlers."),
    "B09993HV2T": ("Kids Play Tunnel Tent", "outdoor", "3-6", False,
                   "A pop-up crawl tunnel for indoor or outdoor play. Folds flat for storage."),
    "B0C3QX5ZSX": ("Laser Tag Set of 2", "outdoor", "8-14", False,
                   "Two infrared laser tag blasters for backyard battles. A screen-free hit with siblings."),
    "B07Y1257KV": ("BooTaa Foam Glider Airplanes (4-Pack)", "outdoor", "3-12", False,
                   "Large throw-and-fly foam airplanes. Cheap, durable fun at the park."),
    "B085W24N3Q": ("WhiteFang Complete Skateboard for Beginners", "outdoor", "8-99", False,
                   "A complete 31-inch skateboard for beginners and teens, ready to ride."),
    "B001I912SQ": ("SKLZ Pro Mini Over-the-Door Basketball Hoop", "outdoor", "6-99", False,
                   "An over-the-door hoop with a breakaway rim. Basketball in the bedroom, all winter."),
    "B0BYV7P9X7": ("MTEN Pickleball Paddle Set of 4", "outdoor", "10-99", False,
                   "Four paddles and balls to play pickleball as a family. Great for teens."),
    "B089HD11JD": ("Zebco Youth Spincast Fishing Rod", "outdoor", "5-12", False,
                   "A floating kids' rod and reel combo, ready for a first fishing trip."),
    "B00D3EQB3K": ("RoyalBaby Freestyle Kids Bike", "outdoor", "3-9", True,
                   "A sturdy kids' bike with training wheels and two brakes. The classic big gift."),
    "B0CCNPV7NZ": ("Gyroor G13 All-Terrain Hoverboard", "outdoor", "8-99", False,
                   "An off-road hoverboard with big tires and lights. A wow gift for older kids and teens."),
    # ---------- Dolls ----------
    "B0B2B8FBL2": ("Disney Princess Aurora Fashion Doll", "dolls", "3-8", False,
                   "Aurora in her signature gown, from Mattel. A princess gift under $10."),
    "B0CMG7Q5FC": ("Monster High Spectra Vondergeist Doll", "dolls", "4-12", False,
                   "Spectra with her pet ghost and fashion accessories, for Monster High fans."),
    "B00EWLNMGC": ("Twins 13-Inch Realistic Soft Body Baby Doll", "dolls", "2-6", False,
                   "A soft, realistic baby doll for little ones who love to cuddle and care."),
    "B0027YRSFC": ("Little Tikes Classic Doll Stroller", "dolls", "2-5", False,
                   "A sturdy toy stroller sized for toddlers to push dolls and plush around."),
    "B09NP2P25T": ("Barbie Fashionistas Ultimate Closet", "dolls", "3-8", False,
                   "A portable closet with outfits and accessories for endless Barbie styling."),
    "B09NQMQ897": ("Barbie Careers Soccer Player Doll", "dolls", "3-8", False,
                   "Barbie ready for the field with a ball and uniform. Under $10."),
    "B0DSCJ5LZ2": ("Unicorn Academy Rory & Storm Set", "dolls", "4-8", False,
                   "Rory and her unicorn Storm from the Unicorn Academy series."),
    "B08V1R73H9": ("Barbie Dreamhouse", "dolls", "3-8", True,
                   "Three stories with a pool, slide and elevator. The ultimate Barbie gift."),
    "B003ADVR3S": ("KidKraft Chelsea Doll Cottage", "dolls", "3-8", False,
                   "A wooden dollhouse with furniture sized for small dolls. A classic heirloom-style gift."),
    "B08DRQ9HLR": ("Fisher-Price Little People Disney Princess Figures", "dolls", "1-5", False,
                   "Chunky Disney Princess figures made for toddler hands."),
    # ---------- Pretend play ----------
    "B07PBXRJ7G": ("Melissa & Doug Dust! Sweep! Mop! Set", "pretend-play", "3-6", False,
                   "Kid-size broom, mop and duster so little helpers can clean along with you."),
    "B07B7319TG": ("LeapFrog Shapes and Sharing Picnic Basket", "pretend-play", "1-3", False,
                   "A picnic basket with play food that teaches shapes, colors and sharing."),
    "B00K89KU80": ("VTech Learn & Discover Pretty Purse", "pretend-play", "1-3", False,
                   "A toddler purse with a toy phone, keys and songs."),
    "B07VNB8BV9": ("Melissa & Doug Get Well Doctor Kit", "pretend-play", "3-6", False,
                   "A wooden doctor kit with stethoscope and tools for playing doctor."),
    "B0C6LHG3D2": ("Pretend Play Food Cutting Set (78 Pieces)", "pretend-play", "3-6", False,
                   "Play fruits, veggies and dishes that 'cut' apart. Perfect with a play kitchen."),
    "B0CPMX764D": ("Bluey Unicorse & Bob Bilby Hand Puppets", "pretend-play", "3-6", False,
                   "Plush hand puppets of Unicorse and Bob Bilby from Bluey, for puppet shows at home."),
    "B07J6TJR2G": ("Melissa & Doug Safari Buddies Hand Puppets", "pretend-play", "2-6", False,
                   "Six soft safari animal puppets for storytelling and puppet shows."),
    "B0DQ6R6CXX": ("Bluey and Bingo Supermarket Playset", "pretend-play", "3-6", False,
                   "A Bluey supermarket with figures and shopping accessories for pretend play."),
    "B08W5DGL1V": ("PAW Patrol Mighty Lookout Tower", "pretend-play", "3-6", False,
                   "A big Lookout Tower playset with figures and vehicles. The PAW Patrol showpiece gift."),
    "B0B4Y639SN": ("PAW Patrol 10th Anniversary All Paws on Deck Figures", "pretend-play", "3-6", False,
                   "A 10-figure PAW Patrol gift pack with the whole team."),
    "B0CHJ5LCTW": ("REXBETI 10-Piece Kids Tool Set with Real Tools", "pretend-play", "4-12", False,
                   "Real, kid-sized hand tools in a case. Perfect for building projects with a grown-up."),
    "B083XNCRS3": ("Bluey Family Figure 4-Pack", "pretend-play", "3-6", False,
                   "Bluey, Bingo, Bandit and Chilli figures. A small gift every Bluey fan wants."),
    # ---------- Superheroes ----------
    "B07PQFT83F": ("Disney Store Buzz Lightyear Talking Action Figure", "superheroes", "3-8", True,
                   "The Disney Store Buzz with wings, lights and phrases from Toy Story."),
    "B077YYP739": ("Transformers Heroic Optimus Prime", "superheroes", "6-10", False,
                   "Optimus Prime converts from robot to truck. A classic for Transformers fans."),
    "B0CP481DTZ": ("Spidey and His Amazing Friends Figure Set", "superheroes", "3-6", False,
                   "Spidey and friends figures from the Disney Junior show for preschool heroes."),
    "B0CVQY49DG": ("Marvel Legends Series Wolverine Figure", "superheroes", "14-99", False,
                   "A detailed 6-inch collector figure for teen and adult Marvel fans."),
    "B07WFHSFYN": ("DC Batman Interactive Gauntlet", "superheroes", "4-12", False,
                   "A wearable Batman gauntlet with lights and sounds for dress-up missions."),
    # ---------- Tech & gadgets ----------
    "B0FD44PTYN": ("Amazon Echo Dot Kids", "tech", "5-12", False,
                   "A kid-friendly smart speaker with parental controls, music, stories and alarms."),
    "B09QW9Z6FX": ("Kids Walkie Talkies, Rechargeable 3-Pack", "tech", "5-12", False,
                   "Three rechargeable walkie talkies for backyard adventures and camping."),
    "B083BCTLP5": ("10-Inch LCD Writing Tablet", "tech", "3-8", False,
                   "A mess-free drawing tablet that erases with one button. Great for car rides."),
    "B08FCYJTJR": ("Tonies Lightning McQueen Audio Figure", "tech", "3-8", False,
                   "Adds Cars stories and songs to a Toniebox. A perfect add-on gift."),
    "B09V6VCQ5P": ("Tonies The Grinch Audio Figure", "tech", "4-8", False,
                   "The Grinch story for the Toniebox. A festive stocking stuffer for Tonie owners."),
    "B0GPGVWMTF": ("Tamagotchi Paradise", "tech", "6-14", False,
                   "The newest Tamagotchi with a zoomable world and more pets to raise."),
    "B0CCRM6JKG": ("Little Tikes Story Dream Machine: Eric Carle", "tech", "3-6", False,
                   "A storytime projector with The Very Hungry Caterpillar stories, for bedtime."),
    "B0CSD1FZXN": ("VTech KidiZoom Smartwatch DX4", "tech", "4-12", False,
                   "A kids' smartwatch with camera, games and activity challenges, no phone needed."),
    "B085WPHTHW": ("Ruko 1088 Smart Robot", "tech", "4-9", False,
                   "A large programmable robot kids control by remote or app. Big wow factor."),
    "B07CMS5Q6P": ("Logitech G305 Wireless Gaming Mouse", "tech", "12-99", False,
                   "A fast, light wireless gaming mouse with long battery life. A teen gamer favorite."),
    "B0F66KLYVH": ("Donkey Kong Bananza (Nintendo Switch 2)", "tech", "8-99", False,
                   "A big new 3D Donkey Kong adventure for Switch 2 owners."),
    "B0F66GQLHH": ("Mario Kart World (Nintendo Switch 2)", "tech", "6-99", True,
                   "The newest Mario Kart for Switch 2. The game the whole family will play."),
    "B0D41XL87F": ("Govee RGBIC Smart Table Lamp 2", "tech", "10-99", False,
                   "A color-changing bedside lamp with app control and music sync. A teen room upgrade."),
    # ---------- Cars & RC ----------
    "B00Y53V7XM": ("VTech Drop and Go Dump Truck", "vehicles", "0-3", False,
                   "Drop blocks in, watch them dump out. A sing-along truck for babies and toddlers."),
    "B01EYUMENC": ("TOMY John Deere Sandbox Vehicle Set", "vehicles", "1-5", False,
                   "A sturdy dump truck and tractor built for the sandbox. Under $15."),
    "B07GWPVCZK": ("Threeking RC Flip Stunt Car", "vehicles", "6-12", False,
                   "A double-sided stunt car that flips and spins. Tough enough for crashes."),
    "B0CZDQ7MCV": ("BEZGAR 1:20 RC Monster Truck", "vehicles", "3-8", False,
                   "A remote-control monster truck with big tires, easy to drive for younger kids."),
    "B0D7PTHTGW": ("Hot Wheels Barbie RC Corvette", "vehicles", "4-8", False,
                   "A pink remote-control Corvette that fits Barbie in the driver's seat."),
    "B002ZCZ0F6": ("Hot Wheels 5-Pack of Cars", "vehicles", "3-99", False,
                   "Five die-cast Hot Wheels cars for about $6. The ultimate stocking stuffer."),
    "B00EX5K1GG": ("Melissa & Doug K's Kids Pull-Back Vehicles", "vehicles", "1-3", False,
                   "Soft pull-back vehicles safe for babies and toddlers."),
    "B07T5Z3XDV": ("JOYIN Emergency Vehicle Toy Set (4-Pack)", "vehicles", "3-6", False,
                   "Police car, fire truck, ambulance and more with lights and sounds."),
    "B07QGG9YXT": ("CAT Construction Fleet 10-Inch Dump Truck", "vehicles", "3-6", False,
                   "A big CAT dump truck with lights and sounds for construction-loving kids."),
    "B0CCCZSR4W": ("JOYIN Light-Up Monster Trucks (3-Pack)", "vehicles", "2-5", False,
                   "Press-and-go monster trucks with lights. No batteries to change for toddlers."),
    "B09BW4241F": ("Hot Wheels Track Builder Unlimited", "vehicles", "4-10", False,
                   "Track pieces and connectors to build loops and jumps. Includes a car."),
    "B01ARGC5F4": ("Hot Wheels Criss Cross Crash Track Set", "vehicles", "5-10", True,
                   "A motorized figure-eight track built for crashes. A Hot Wheels classic."),
    "B008LQXR82": ("Green Toys Airplane", "vehicles", "1-4", False,
                   "A chunky airplane made from recycled plastic. Dishwasher safe and toddler tough."),
    "B07QGKGTK7": ("CAT Construction Mini Crew 3-Pack", "vehicles", "3-6", False,
                   "A 7-inch dump truck, loader and excavator for sandbox and floor play."),
    # ---------- Plush ----------
    "B01AC7SF7K": ("GUND Baby Flappy the Elephant", "plush", "0-3", False,
                   "An animated elephant that sings and plays peekaboo with its ears."),
    "B083FM3R87": ("Aurora Mini Flopsie Ginger Cat", "plush", "3-99", False,
                   "A soft 8-inch cat plush with over 75,000 ratings. A sweet small gift."),
    "B084JCXB87": ("Care Bears Cheer Bear 14-Inch Plush", "plush", "4-99", False,
                   "Cheer Bear in super-soft plush, for kids and nostalgic parents alike."),
    "B08GYCRTL4": ("Bluey & Bingo Plush 2-Pack", "plush", "3-8", False,
                   "Soft Bluey and Bingo plush toys. A must-have for Bluey fans."),
    "B08BQY696Y": ("MaoGoLan 47-Inch Giant Teddy Bear", "plush", "3-99", False,
                   "A huge, huggable teddy bear. A memorable gift for kids and teens."),
    "B08G1WJMGW": ("Squishmallows 16-Inch Plush", "plush", "3-99", False,
                   "A big, super-soft Squishmallow. The plush teens and tweens actually ask for."),
    "B086FXDT59": ("GUND Sesame Street Elmo Take Along Buddy", "plush", "1-5", False,
                   "A 13-inch Elmo plush perfect for toddlers to carry everywhere."),
    "B0BTMZQ7V9": ("The Petting Zoo Hedgehog Plush", "plush", "3-99", False,
                   "A soft hedgehog plush under $10, a sweet stocking stuffer."),
    "B0865TT94B": ("Jellycat Little Pig", "plush", "0-99", False,
                   "Jellycat's famously soft little pig. A premium plush loved by all ages."),
    "B07CYWR2PH": ("Harry Potter Dobby Plush", "plush", "3-99", False,
                   "Dobby the house-elf in soft plush, for Harry Potter fans."),
    # ---------- Arts & crafts ----------
    "B07D4T2XKB": ("Crayola Mini Twistables Crayons (50 Count)", "arts", "3-10", False,
                   "No-sharpen twist crayons in 50 colors. A classic stocking stuffer."),
    "B09PGVGCH5": ("Bluey Aqua Art Water Reveal", "arts", "3-6", False,
                   "Paint with water to reveal Bluey pictures, then watch them fade and do it again."),
    "B0DBNSG2XN": ("Elmer's Color Rush Slime Kit", "arts", "6-12", False,
                   "Make color-changing slime with Elmer's glue and activator. Slime-lovers' favorite."),
    "B08LDGHNXR": ("33-Cup Jumbo Premade Slime Kit", "arts", "6-12", False,
                   "33 cups of premade slime plus add-ins. No mixing needed, instant fun."),
    "B09NBF3ZPJ": ("Fashion Designer Kit with 6 Mannequins", "arts", "6-12", False,
                   "Fabrics, mannequins and tools to design and dress mini fashion creations."),
    "B009VE38D2": ("Spirograph Design Set Collector's Tin", "arts", "8-99", False,
                   "The classic Spirograph in a tin. Endless spiral art, no screens."),
    "B00II021GK": ("Hape All-in-1 Magnetic Kids Easel", "arts", "3-8", True,
                   "A height-adjustable easel with a chalkboard, whiteboard and paper roll."),
    "B084BTPVFQ": ("Kinetic Sand 3.25 lb Beach Sand", "arts", "3-8", False,
                   "Moldable sand that never dries out. Calm, creative sensory play."),
    "B083Z3JMGP": ("Creativity for Kids Mermaid Mini Garden", "arts", "6-12", False,
                   "Plant and grow a mini terrarium garden with mermaid decorations."),
    "B00JBKVN8S": ("Brother XM2701 Sewing Machine", "arts", "13-99", False,
                   "A lightweight, beginner-friendly sewing machine for creative teens."),
}
